# Generated by Django 5.1.6 on 2025-05-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_orderitem_order_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
